name: ci

on:
  push:
  workflow_dispatch:

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build image
        run: |
          docker buildx build --load --platform linux/amd64 -t test .
      -
        name: Run
        run: |
          docker run --rm -v .:/workdir --workdir=/workdir --platform linux/amd64 test bash -c 'cargo build -v'

  arm64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build image
        run: |
          docker buildx build --load --platform linux/arm64 -t test .
      -
        name: Run
        run: |
          docker run --rm -v .:/workdir --workdir=/workdir --platform linux/arm64 test bash -c 'cargo build -v'
